<?php

/**
 * @file
 * Contains override_permission_file_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function override_permission_file_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the override_permission_file_entity module.
    case 'help.page.override_permission_file_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is override Access Handle class removed effect of <code>View own private files</code> permission. 
                More at <a href="https://github.com/digitalutsc/islandora_lite_docs/issues/31#issuecomment-1025840190">https://github.com/digitalutsc/islandora_lite_docs/issues/31#issuecomment-1025840190</a>') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function override_permission_file_entity_theme() {
  return [
    'override_permission_file_entity' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_info_alter().
 *
 * Extends the core file entity to be fieldable. The file type is used as the
 * bundle key.
 */
function override_permission_file_entity_entity_type_alter(&$entity_types) {
    /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */

    // Unset the Access class in defined $entity_types['files']
    $entity_types['file']->setAccessClass(null);


    //print_log("---------Afterwards---------");
    //print_log($entity_types['file']);
}

/**
 * Implements hook_install().
 *
 * @return void
 */
function override_permission_file_entity_install() {
    //print_log("======override_permission_file_entity_install=========");

    // set the weight to make sure this module enabled after File Entity module is enabled
    module_set_weight('override_permission_file_entity', 10000);
}